### ISSUE TITLE
Could you add support for offline music?

### ISSUE THREAD

**Issue by pmarimon** [tvillarete/ipod-classic-js#102]
I don't like the idea of only being able to listen to music in shuffle mode and with ads in free spotify and I don't want to pay (I can't) for premium services, so I have all my music offline in my iPhone's music app. Is there any way to add support for offline music?

**Comment by tvillarete** [comment]
Hey @pmarimon, unfortunately this project was designed with streaming in mind and thus will most likely never work offline – that is unless someone like you wants to modify what I've written to support it!

Due to Apple's limitations on a website's ability to read local files like your iPhone's music library, I don't see this ever being possible on iOS; but it could definitely be done on a desktop computer. Thanks for the suggestion, and sorry I couldn't help out more here. Best of luck!
