### ISSUE TITLE
Songs stop playing in the background-iPhone

### ISSUE THREAD

**Issue by Seryi358** [tvillarete/ipod-classic-js#110]
Hi, I'm using this web player on iPhone with iOS 15.5 and Safari; I have the problem that songs stop playing in the background, whether the device is turned off or using another app in the meantime. Thanks

**Comment by tvillarete** [comment]
Hey @Seryi358,

This usually happens when you've added the app to your home screen. There are some limitations to websites that have been added to the home screen via Safari Bookmarks. Safari Bookmarks for some reason can't play audio when the app is backgrounded whereas the default Safari app can ([link to StackOverflow discussion](https://stackoverflow.com/questions/4557991/ios-background-audio-in-a-web-app)).

Unfortunately there's nothing I can do about this besides suggest that you use the main Safari app if you want to listen in the background 🤷
