### ISSUE TITLE
Volume 

### ISSUE THREAD

**Issue by EvanBarron99** [tvillarete/ipod-classic-js#134]
Ok so I wish controlling the volume with the iPod actually change the volume.

**Comment by tvillarete** [comment]
Hey @EvanBarron99,

I absolutely agree with you that it would be cool to change volume using the scroll wheel, but unfortunately this is a limitation of iOS (I'm assuming you're using an iPhone, iPad, or iPod Touch). Apple only allows you to change volume using the physical volume buttons on the device, so there's no way for me to do it through the iPod interface. 

If they do ever loosen restrictions for volume control, I will happily update this, but for now there's not much I can do. Thanks for the request though, and hopefully you've enjoyed using it otherwise!
