### ISSUE TITLE
when i open the website, nothing pops up

### ISSUE THREAD

**Issue by pancakeeaterfr** [tvillarete/ipod-classic-js#137]
basically the title. when i go onto the website, its all just a blank screen. i tried adding it to home screen, but, it was still blank. even tried going on other devices, still blank. ty:)

**Comment by tvillarete** [comment]
Hey @pancakeeaterfr, thanks for the heads up! Looks like Apple changed their API which broke my code since it always references the latest version. A single `?` (or lack thereof) caused my entire app to crash 😅 

[Link to relevant code](https://github.com/tvillarete/ipod-classic-js/commit/c9618e391535a72672d5c97a2d20099da1587ff2#diff-4e5b878e60182a4ecb7cacc9225826d0d1923f55fb2929c6cdcef8966b8e77ebR14)

Should be all fixed now 👍
