### ISSUE TITLE
ngrok.io blocked on corporate network

### ISSUE THREAD

**Issue by captbaritone** [tvillarete/ipod-classic-js#20]
![Screen Shot 2021-06-23 at 10 39 15 AM](https://user-images.githubusercontent.com/162735/123143492-81127300-d40f-11eb-8002-054762fc56c9.png)

Awesome project!

**Comment by jamy015** [comment]
Appears to work fine for me.

**Comment by captbaritone** [comment]
Interesting. When I curl that url I get:

```bash
$ curl https://b7d1fdb16506.ngrok.io/login
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

**Comment by captbaritone** [comment]
Ah, looks like my corporate network was blocking ngrok.io.

**Comment by captbaritone** [comment]
I've updated the title to reflect what's really going on. Feel free to close if you think this is in-actionable, or leave open if you want to track/explore solutions.

**Comment by tvillarete** [comment]
Hey @captbaritone, good to know that Ngrok doesn't work in certain work environments 😅 I unfortunately can't really do much about this unless I paid for a [higher tier](https://ngrok.com/pricing) to get access to custom domains (which still may or may not work). The URL in that case would appear to be from a different domain rather than ngrok, which might circumvent your corporate site ban, but I'd have to test it to be sure.

Going to close this one, but I appreciate the heads up!
