### ISSUE TITLE
Lockscreen player doesn't display cover art - move to musickit JS V3

### ISSUE THREAD

**Issue by tedhosmann** [tvillarete/ipod-classic-js#21]
Not sure if you are maintaining this project still but musicKit v3 is now available with a fix for showing the cover art on the lock screen player. 
https://js-cdn.music.apple.com/musickit/v3/docs/index.html?path=/story/tech-notes-migrating-to-musickit-js-3--page

**Comment by tvillarete** [comment]
This is great to know! Was very much looking forward to it at WWDC. I'll look into adding v3 support, though the one thing that will most likely prevent me from upgrading would be lack of TypeScript support, which I had to find a 3rd party package for (and isn't very consistent). I'm assuming many of the types have changed which might cause some issues, but it's worth a shot anyway 👍

**Comment by tedhosmann** [comment]
Might be a fun to add Music Video support too now that it is supported in V3 (and was supported on iPod Classic).

**Comment by crutchcorn** [comment]
I could write an updated `@types/apple-music-api` update @tvillarete. Would that help unblock this?

**Comment by tvillarete** [comment]
That would definitely unblock it! Other than types, the migration is pretty painless as far as I can tell – just a couple of calls to tweak here and there

**Comment by crutchcorn** [comment]
@tvillarete I'll see what I can do in terms of strict/accurate TS typings within the next few days. Something you could actually do to help me test this (if you have time, if not, no worries) is by building the v3 migration with `any` types (basically, just side step TS temporarily). If we can get a version that has its functionality working (say, in a separate branch), then when I have the typings ready we can do a simple drop-in to verify that the typings are at least correct enough for the app's usage. We then don't have to wait for the `npm` package to publish in order to test our TS typings (since we can install them locally in the project until then)

Like I said though, if not no worries

**Comment by tvillarete** [comment]
@crutchcorn sounds great. I'm diving in already and it looks like there are some significant changes to how v3 connects to the Apple Music API, with little to no documentation... nothing I can't figure out with a bunch of `console.log`s but it's definitely not as straightforward as I thought 😅 

I'm working on a branch with a bunch of casting, like you suggested, and will send you the branch as soon as I get it all working. Thanks!

**Comment by tvillarete** [comment]
@crutchcorn Just a heads up, I've filed a PR to upgrade to V3 and marked everywhere that will need to have the types updated. Since this update fixes so many bugs and adds a lot of features, I'm gonna go ahead and merge this PR in after doing some testing and we can address the types later.

I actually talked with an Apple dev recently regarding upgrading to V3 which answered quite a few questions of mine. From the conversation:

- We may see official TypeScript support from Apple in the near future. It's probably not worth it to create a 3rd party package. 
- MusicKit JS was actually built using TS, but they just haven't published types (surprising, given the lack of documentation)
- V3 Documentation is likely to improve, but it's nowhere near what would be necessary to generate TypeScript types. I gave them a few suggestions on what I'd like to see
