### ISSUE TITLE
Better mobile view

### ISSUE THREAD

**Issue by crutchcorn** [tvillarete/ipod-classic-js#28]
I would love to use this app as a daily driver for Spotify on my mobile device. I'm wondering if we're able to make the view take up the entire screenspace on a mobile device and pin the scroll wheel closer to the bottom of the screen.

**Comment by tvillarete** [comment]
Hey @crutchcorn, totally agree mobile could be better! I did some experimentation a while ago on what looks best for mobile devices, and as you can see from the screenshot, the bigger the viewport is the stranger the layout gets as it stretches. My opinion at the time was that it was better to just limit the height rather than stretch it out, but I'm open to other opinions as well. Thanks!

<img width="1456" alt="Screen Shot 2021-06-24 at 7 48 03 PM" src="https://user-images.githubusercontent.com/21055469/123362174-1d7a6980-d525-11eb-8a6a-648ec48ea04f.png">

**Comment by crutchcorn** [comment]
For sure, I feel that. 

I personally don't mind that stretching, even tho it's certainly not in the design spirit of the original

I guess my thing is that I'd rather have it aligned to the bottom of the screen (rather than the top, where it seems to align on mobile right now), as it would allow me to more easily access the scroll wheel

**Comment by tvillarete** [comment]
I like that idea! I'll file a quick fix to align it to the bottom and then work on figuring out a better utilization of the full screen. Thanks for the suggestion!
