### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by minefox199** [tvillarete/ipod-classic-js#82]
i can't log in with Spotify plz help me from my school and gaming pc

**Comment by TheAwesome98-Real** [comment]
if you want help please give information

**Comment by minefox199** [comment]
ok so when i try to log in with Spotify it doesn't show my music or playlist

**Comment by minefox199** [comment]
or did a code got deleted or is it not responding to Spotify servers?

**Comment by TheAwesome98-Real** [comment]
ok well i dont have spotify so i cant see if there is an error in console but im pretty sure apple music also didnt work so probably the handling code for login is outdated

**Comment by tvillarete** [comment]
Hey @TheAwesome98-Real, Apple Music was indeed in a broken state due to an expired access token on my end. I've refreshed it and it should be working again; feel free to give it a try and let me know.

@minefox199 Just to be clear – you'll need a Spotify Premium account to be able to access your music from within the iPod interface. Not sure if this is the issue you're running into. Can you give me the name of the browser you're using?

**Comment by TheAwesome98-Real** [comment]
ah nice, thanks

**Comment by minefox199** [comment]
google chrome

**Comment by tvillarete** [comment]
Gonna close this issue as what @minefox199  was most likely running into is the school's firewall. At least back when I was in high school, Spotify was a blacklisted site

**Comment by minefox199** [comment]
now I can sign into my spotify account
