### ISSUE TITLE
When I run `yarn start` in command prompt I am getting the error `'yarn' is not recognized as an internal or external command`

### ISSUE THREAD

**Issue by Utsav-Murudi** [tvillarete/ipod-classic-js#90]
I am pretty that it is my ignorance of opening files that is causing this issue but what I basically did was open the file directory where `yarn.lock` is located and type cmd in the address bar of that file directory so that it opens that folder directory in command prompt. And then I ran the command `yarn start` and now I am getting the error `'yarn' is not recognized as an internal or external command,
operable program or batch file.`

Can somebody please help me with this....

**Comment by tvillarete** [comment]
Hi @Utsav-Murudi,

In order to use the `yarn` command, you first have to install Yarn onto your computer. It looks like you're using Windows, so try following[ these instructions](https://classic.yarnpkg.com/en/docs/install#windows-stable) on Yarn's website (Click the "Alternatives" dropdown to see how to install with an MSI file) and then it should work. Make sure to run `yarn install` to download the proper dependencies before running `yarn start`

**Comment by Utsav-Murudi** [comment]
Thanks a lot @tvillarete!
